version: '3.8'

services:
  # client:
  #   build:
  #     context: ./client/hackyourcareer
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   command: ["npm", "start"]

  app:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./service/hackyourcareer/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
